// Fixed admission list from the approved channel specification appendix.
export const FAL_ENDPOINT_IDS: readonly string[] = [
    // Images (12).
    "fal-ai/flux-2-pro",
    "fal-ai/flux-2-pro/edit",
    "fal-ai/nano-banana",
    "fal-ai/nano-banana/edit",
    "fal-ai/nano-banana-pro",
    "fal-ai/nano-banana-pro/edit",
    "fal-ai/nano-banana-2",
    "fal-ai/nano-banana-2/edit",
    "openai/gpt-image-2",
    "openai/gpt-image-2/edit",
    "bytedance/seedream/v5/pro/text-to-image",
    "bytedance/seedream/v5/pro/edit",
    // Videos (24).
    "fal-ai/kling-video/v3/pro/text-to-video",
    "fal-ai/kling-video/v3/pro/image-to-video",
    "fal-ai/kling-video/v3/standard/text-to-video",
    "fal-ai/kling-video/v3/standard/image-to-video",
    "fal-ai/veo3.1",
    "fal-ai/veo3.1/image-to-video",
    "fal-ai/veo3.1/first-last-frame-to-video",
    "fal-ai/veo3.1/fast",
    "fal-ai/veo3.1/fast/image-to-video",
    "fal-ai/veo3.1/fast/first-last-frame-to-video",
    "bytedance/seedance-2.0/text-to-video",
    "bytedance/seedance-2.0/image-to-video",
    "bytedance/seedance-2.0/fast/text-to-video",
    "bytedance/seedance-2.0/fast/image-to-video",
    "wan/v2.6/text-to-video",
    "wan/v2.6/image-to-video",
    "fal-ai/minimax/hailuo-2.3/pro/text-to-video",
    "fal-ai/minimax/hailuo-2.3/pro/image-to-video",
    "fal-ai/minimax/hailuo-2.3/standard/text-to-video",
    "fal-ai/minimax/hailuo-2.3/standard/image-to-video",
    "fal-ai/ltx-2.3/text-to-video",
    "fal-ai/ltx-2.3/text-to-video/fast",
    "fal-ai/ltx-2.3/image-to-video",
    "fal-ai/ltx-2.3/image-to-video/fast",
];
