import type { FalProfileDescriptor } from "./profile-types";

// Each entry is reviewed independently against its exact captured OpenAPI.
export const imageProfileDescriptors: readonly FalProfileDescriptor[] = [
    {
        endpointId: "fal-ai/flux-2-pro",
        submitPath: "/fal-ai/flux-2-pro",
        resultPath: "/fal-ai/flux-2-pro/requests/{request_id}",
        defaults: {"image_size": "landscape_4_3", "output_format": "jpeg"},
        fields: [{"name": "image_size", "common": "size", "valueMap": {"1:1": "square_hd", "4:3": "landscape_4_3", "3:4": "portrait_4_3", "16:9": "landscape_16_9", "9:16": "portrait_16_9"}}, {"name": "output_format"}, {"name": "seed"}, {"name": "safety_tolerance"}, {"name": "enable_safety_checker"}],
        media: [],
    },
    {
        endpointId: "fal-ai/flux-2-pro/edit",
        submitPath: "/fal-ai/flux-2-pro/edit",
        resultPath: "/fal-ai/flux-2-pro/edit/requests/{request_id}",
        defaults: {"image_size": "auto", "output_format": "jpeg"},
        fields: [{"name": "image_size", "common": "size", "valueMap": {"1:1": "square_hd", "4:3": "landscape_4_3", "3:4": "portrait_4_3", "16:9": "landscape_16_9", "9:16": "portrait_16_9"}}, {"name": "output_format"}, {"name": "seed"}, {"name": "safety_tolerance"}, {"name": "enable_safety_checker"}],
        media: [{"field": "image_urls", "mode": "many", "role": "references", "required": true}],
    },
    {
        endpointId: "fal-ai/nano-banana",
        submitPath: "/fal-ai/nano-banana",
        resultPath: "/fal-ai/nano-banana/requests/{request_id}",
        defaults: {"aspect_ratio": "1:1", "output_format": "png", "num_images": 1},
        fields: [{"name": "aspect_ratio", "common": "size"}, {"name": "output_format"}, {"name": "seed"}, {"name": "safety_tolerance"}],
        media: [],
    },
    {
        endpointId: "fal-ai/nano-banana/edit",
        submitPath: "/fal-ai/nano-banana/edit",
        resultPath: "/fal-ai/nano-banana/edit/requests/{request_id}",
        defaults: {"aspect_ratio": "auto", "output_format": "png", "num_images": 1},
        fields: [{"name": "aspect_ratio", "common": "size"}, {"name": "output_format"}, {"name": "seed"}, {"name": "safety_tolerance"}],
        media: [{"field": "image_urls", "mode": "many", "role": "references", "required": true}],
    },
    {
        endpointId: "fal-ai/nano-banana-pro",
        submitPath: "/fal-ai/nano-banana-pro",
        resultPath: "/fal-ai/nano-banana-pro/requests/{request_id}",
        defaults: {"aspect_ratio": "1:1", "output_format": "png", "resolution": "1K", "num_images": 1},
        fields: [{"name": "aspect_ratio", "common": "size"}, {"name": "output_format"}, {"name": "resolution", "common": "resolution"}, {"name": "seed"}, {"name": "safety_tolerance"}, {"name": "system_prompt"}, {"name": "enable_web_search"}],
        media: [],
    },
    {
        endpointId: "fal-ai/nano-banana-pro/edit",
        submitPath: "/fal-ai/nano-banana-pro/edit",
        resultPath: "/fal-ai/nano-banana-pro/edit/requests/{request_id}",
        defaults: {"aspect_ratio": "auto", "output_format": "png", "resolution": "1K", "num_images": 1},
        fields: [{"name": "aspect_ratio", "common": "size"}, {"name": "output_format"}, {"name": "resolution", "common": "resolution"}, {"name": "seed"}, {"name": "safety_tolerance"}, {"name": "system_prompt"}, {"name": "enable_web_search"}],
        media: [{"field": "image_urls", "mode": "many", "role": "references", "required": true}],
    },
    {
        endpointId: "fal-ai/nano-banana-2",
        submitPath: "/fal-ai/nano-banana-2",
        resultPath: "/fal-ai/nano-banana-2/requests/{request_id}",
        defaults: {"aspect_ratio": "auto", "output_format": "png", "resolution": "1K", "num_images": 1},
        fields: [{"name": "aspect_ratio", "common": "size"}, {"name": "output_format"}, {"name": "resolution", "common": "resolution"}, {"name": "seed"}, {"name": "safety_tolerance"}, {"name": "system_prompt"}, {"name": "enable_web_search"}, {"name": "thinking_level"}],
        media: [],
    },
    {
        endpointId: "fal-ai/nano-banana-2/edit",
        submitPath: "/fal-ai/nano-banana-2/edit",
        resultPath: "/fal-ai/nano-banana-2/edit/requests/{request_id}",
        defaults: {"aspect_ratio": "auto", "output_format": "png", "resolution": "1K", "num_images": 1},
        fields: [{"name": "aspect_ratio", "common": "size"}, {"name": "output_format"}, {"name": "resolution", "common": "resolution"}, {"name": "seed"}, {"name": "safety_tolerance"}, {"name": "system_prompt"}, {"name": "enable_web_search"}, {"name": "thinking_level"}],
        media: [{"field": "image_urls", "mode": "many", "role": "references", "required": true}],
    },
    {
        endpointId: "openai/gpt-image-2",
        submitPath: "/fal-ai/gpt-image-2",
        resultPath: "/fal-ai/gpt-image-2/requests/{request_id}",
        defaults: {"image_size": "landscape_4_3", "output_format": "png", "quality": "high", "num_images": 1},
        fields: [{"name": "image_size", "common": "size", "valueMap": {"1:1": "square_hd", "4:3": "landscape_4_3", "3:4": "portrait_4_3", "16:9": "landscape_16_9", "9:16": "portrait_16_9"}}, {"name": "output_format"}, {"name": "quality", "common": "quality"}, {"name": "background"}],
        media: [],
    },
    {
        endpointId: "openai/gpt-image-2/edit",
        submitPath: "/fal-ai/gpt-image-2/edit",
        resultPath: "/fal-ai/gpt-image-2/edit/requests/{request_id}",
        defaults: {"image_size": "auto", "output_format": "png", "quality": "high", "num_images": 1},
        fields: [{"name": "image_size", "common": "size", "valueMap": {"1:1": "square_hd", "4:3": "landscape_4_3", "3:4": "portrait_4_3", "16:9": "landscape_16_9", "9:16": "portrait_16_9"}}, {"name": "output_format"}, {"name": "quality", "common": "quality"}, {"name": "background"}],
        media: [{"field": "image_urls", "mode": "many", "role": "references", "required": true}],
    },
    {
        endpointId: "bytedance/seedream/v5/pro/text-to-image",
        submitPath: "/fal-ai/seedream-5-pro/text-to-image",
        resultPath: "/fal-ai/seedream-5-pro/text-to-image/requests/{request_id}",
        defaults: {"image_size": "auto_2K", "output_format": "jpeg", "num_images": 1},
        fields: [{"name": "image_size", "common": "size", "valueMap": {"1:1": "square_hd", "4:3": "landscape_4_3", "3:4": "portrait_4_3", "16:9": "landscape_16_9", "9:16": "portrait_16_9"}}, {"name": "output_format"}, {"name": "enable_safety_checker"}],
        media: [],
    },
    {
        endpointId: "bytedance/seedream/v5/pro/edit",
        submitPath: "/fal-ai/seedream-5-pro/edit",
        resultPath: "/fal-ai/seedream-5-pro/edit/requests/{request_id}",
        defaults: {"image_size": "auto_2K", "output_format": "jpeg", "num_images": 1},
        fields: [{"name": "image_size", "common": "size", "valueMap": {"1:1": "square_hd", "4:3": "landscape_4_3", "3:4": "portrait_4_3", "16:9": "landscape_16_9", "9:16": "portrait_16_9"}}, {"name": "output_format"}, {"name": "enable_safety_checker"}],
        media: [{"field": "image_urls", "mode": "many", "role": "references", "required": true}],
        propertyConstraints: {"image_urls": {"maxItems": 10}},
    },
];
