import type { FalProfileDescriptor } from "./profile-types";

// Each entry is reviewed independently against its exact captured OpenAPI.
// Seedance max 30 MB is interpreted as decimal 30,000,000 bytes; vendor boundary remains unprobed.
// Constraints attach only to the explicitly documented slot (LTX fast end frame has no format list).
export const videoProfileDescriptors: readonly FalProfileDescriptor[] = [
    {
        endpointId: "fal-ai/kling-video/v3/pro/text-to-video",
        submitPath: "/fal-ai/kling-video/v3/pro/text-to-video",
        resultPath: "/fal-ai/kling-video/v3/pro/text-to-video/requests/{request_id}",
        defaults: {"duration": "5", "aspect_ratio": "16:9", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "aspect_ratio", "common": "size"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "cfg_scale"}, {"name": "shot_type"}, {"name": "negative_prompt"}],
        media: [],
        propertyConstraints: {"prompt": {"type": "string", "minLength": 1, "maxLength": 2500}},
    },
    {
        endpointId: "fal-ai/kling-video/v3/pro/image-to-video",
        submitPath: "/fal-ai/kling-video/v3/pro/image-to-video",
        resultPath: "/fal-ai/kling-video/v3/pro/image-to-video/requests/{request_id}",
        defaults: {"duration": "5", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "cfg_scale"}, {"name": "shot_type"}, {"name": "negative_prompt"}],
        media: [{"field": "start_image_url", "mode": "one", "role": "first", "required": true, "constraints": {"maxBytes": 10485760, "minDimension": 300, "minAspectRatio": 0.4, "maxAspectRatio": 2.5}}, {"field": "end_image_url", "mode": "one", "role": "last", "required": false, "constraints": {"maxBytes": 10485760, "minDimension": 300, "minAspectRatio": 0.4, "maxAspectRatio": 2.5}}],
        propertyConstraints: {"prompt": {"type": "string", "minLength": 1, "maxLength": 2500}},
    },
    {
        endpointId: "fal-ai/kling-video/v3/standard/text-to-video",
        submitPath: "/fal-ai/kling-video/v3/standard/text-to-video",
        resultPath: "/fal-ai/kling-video/v3/standard/text-to-video/requests/{request_id}",
        defaults: {"duration": "5", "aspect_ratio": "16:9", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "aspect_ratio", "common": "size"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "cfg_scale"}, {"name": "shot_type"}, {"name": "negative_prompt"}],
        media: [],
        propertyConstraints: {"prompt": {"type": "string", "minLength": 1, "maxLength": 2500}},
    },
    {
        endpointId: "fal-ai/kling-video/v3/standard/image-to-video",
        submitPath: "/fal-ai/kling-video/v3/standard/image-to-video",
        resultPath: "/fal-ai/kling-video/v3/standard/image-to-video/requests/{request_id}",
        defaults: {"duration": "5", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "cfg_scale"}, {"name": "shot_type"}, {"name": "negative_prompt"}],
        media: [{"field": "start_image_url", "mode": "one", "role": "first", "required": true, "constraints": {"maxBytes": 10485760, "minDimension": 300, "minAspectRatio": 0.4, "maxAspectRatio": 2.5}}, {"field": "end_image_url", "mode": "one", "role": "last", "required": false, "constraints": {"maxBytes": 10485760, "minDimension": 300, "minAspectRatio": 0.4, "maxAspectRatio": 2.5}}],
        propertyConstraints: {"prompt": {"type": "string", "minLength": 1, "maxLength": 2500}},
    },
    {
        endpointId: "fal-ai/veo3.1",
        submitPath: "/fal-ai/veo3.1",
        resultPath: "/fal-ai/veo3.1/requests/{request_id}",
        defaults: {"duration": "8s", "aspect_ratio": "16:9", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "seconds-suffix"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "auto_fix"}, {"name": "safety_tolerance"}, {"name": "seed"}, {"name": "negative_prompt"}],
        media: [],
    },
    {
        endpointId: "fal-ai/veo3.1/image-to-video",
        submitPath: "/fal-ai/veo3.1/image-to-video",
        resultPath: "/fal-ai/veo3.1/image-to-video/requests/{request_id}",
        defaults: {"duration": "8s", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "seconds-suffix"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "auto_fix"}, {"name": "safety_tolerance"}, {"name": "seed"}, {"name": "negative_prompt"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true}],
    },
    {
        endpointId: "fal-ai/veo3.1/first-last-frame-to-video",
        submitPath: "/fal-ai/veo3.1/first-last-frame-to-video",
        resultPath: "/fal-ai/veo3.1/first-last-frame-to-video/requests/{request_id}",
        defaults: {"duration": "8s", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "seconds-suffix"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "auto_fix"}, {"name": "safety_tolerance"}, {"name": "seed"}, {"name": "negative_prompt"}],
        media: [{"field": "first_frame_url", "mode": "one", "role": "first", "required": true}, {"field": "last_frame_url", "mode": "one", "role": "last", "required": true}],
    },
    {
        endpointId: "fal-ai/veo3.1/fast",
        submitPath: "/fal-ai/veo3.1/fast",
        resultPath: "/fal-ai/veo3.1/fast/requests/{request_id}",
        defaults: {"duration": "8s", "aspect_ratio": "16:9", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "seconds-suffix"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "auto_fix"}, {"name": "safety_tolerance"}, {"name": "seed"}, {"name": "negative_prompt"}],
        media: [],
    },
    {
        endpointId: "fal-ai/veo3.1/fast/image-to-video",
        submitPath: "/fal-ai/veo3.1/fast/image-to-video",
        resultPath: "/fal-ai/veo3.1/fast/image-to-video/requests/{request_id}",
        defaults: {"duration": "8s", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "seconds-suffix"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "auto_fix"}, {"name": "safety_tolerance"}, {"name": "seed"}, {"name": "negative_prompt"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true}],
    },
    {
        endpointId: "fal-ai/veo3.1/fast/first-last-frame-to-video",
        submitPath: "/fal-ai/veo3.1/fast/first-last-frame-to-video",
        resultPath: "/fal-ai/veo3.1/fast/first-last-frame-to-video/requests/{request_id}",
        defaults: {"duration": "8s", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "seconds-suffix"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "auto_fix"}, {"name": "safety_tolerance"}, {"name": "seed"}, {"name": "negative_prompt"}],
        media: [{"field": "first_frame_url", "mode": "one", "role": "first", "required": true}, {"field": "last_frame_url", "mode": "one", "role": "last", "required": true}],
    },
    {
        endpointId: "bytedance/seedance-2.0/text-to-video",
        submitPath: "/fal-ai/seedance-2/text-to-video",
        resultPath: "/fal-ai/seedance-2/text-to-video/requests/{request_id}",
        defaults: {"duration": "auto", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "bitrate_mode"}],
        media: [],
    },
    {
        endpointId: "bytedance/seedance-2.0/image-to-video",
        submitPath: "/fal-ai/seedance-2/image-to-video",
        resultPath: "/fal-ai/seedance-2/image-to-video/requests/{request_id}",
        defaults: {"duration": "auto", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "bitrate_mode"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true, "constraints": {"maxBytes": 30000000, "mimeTypes": ["image/jpeg", "image/png", "image/webp"]}}, {"field": "end_image_url", "mode": "one", "role": "last", "required": false, "constraints": {"maxBytes": 30000000, "mimeTypes": ["image/jpeg", "image/png", "image/webp"]}}],
    },
    {
        endpointId: "bytedance/seedance-2.0/fast/text-to-video",
        submitPath: "/fal-ai/seedance-2/fast/text-to-video",
        resultPath: "/fal-ai/seedance-2/fast/text-to-video/requests/{request_id}",
        defaults: {"duration": "auto", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "bitrate_mode"}],
        media: [],
    },
    {
        endpointId: "bytedance/seedance-2.0/fast/image-to-video",
        submitPath: "/fal-ai/seedance-2/fast/image-to-video",
        resultPath: "/fal-ai/seedance-2/fast/image-to-video/requests/{request_id}",
        defaults: {"duration": "auto", "aspect_ratio": "auto", "resolution": "720p", "generate_audio": false},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "bitrate_mode"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true, "constraints": {"maxBytes": 30000000, "mimeTypes": ["image/jpeg", "image/png", "image/webp"]}}, {"field": "end_image_url", "mode": "one", "role": "last", "required": false, "constraints": {"maxBytes": 30000000, "mimeTypes": ["image/jpeg", "image/png", "image/webp"]}}],
    },
    {
        endpointId: "wan/v2.6/text-to-video",
        submitPath: "/fal-ai/wan-26-t2v/text-to-video",
        resultPath: "/fal-ai/wan-26-t2v/text-to-video/requests/{request_id}",
        defaults: {"duration": "5", "aspect_ratio": "16:9", "resolution": "1080p"},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "negative_prompt"}, {"name": "multi_shots"}, {"name": "seed"}, {"name": "enable_prompt_expansion"}, {"name": "enable_safety_checker"}],
        media: [],
        propertyConstraints: {"prompt": {"maxLength": 1500}, "negative_prompt": {"maxLength": 500}},
    },
    {
        endpointId: "wan/v2.6/image-to-video",
        submitPath: "/fal-ai/wan-26-i2v",
        resultPath: "/fal-ai/wan-26-i2v/requests/{request_id}",
        defaults: {"duration": "5", "resolution": "1080p"},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "resolution", "common": "resolution"}, {"name": "negative_prompt"}, {"name": "multi_shots"}, {"name": "seed"}, {"name": "enable_prompt_expansion"}, {"name": "enable_safety_checker"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true, "constraints": {"minDimension": 240, "maxDimension": 7680}}],
        propertyConstraints: {"prompt": {"maxLength": 1500}, "negative_prompt": {"maxLength": 500}},
    },
    {
        endpointId: "fal-ai/minimax/hailuo-2.3/pro/text-to-video",
        submitPath: "/fal-ai/minimax/hailuo-2.3/pro/text-to-video",
        resultPath: "/fal-ai/minimax/hailuo-2.3/pro/text-to-video/requests/{request_id}",
        defaults: {},
        fields: [{"name": "prompt_optimizer"}],
        media: [],
    },
    {
        endpointId: "fal-ai/minimax/hailuo-2.3/pro/image-to-video",
        submitPath: "/fal-ai/minimax/hailuo-2.3/pro/image-to-video",
        resultPath: "/fal-ai/minimax/hailuo-2.3/pro/image-to-video/requests/{request_id}",
        defaults: {},
        fields: [{"name": "prompt_optimizer"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true}],
    },
    {
        endpointId: "fal-ai/minimax/hailuo-2.3/standard/text-to-video",
        submitPath: "/fal-ai/minimax/hailuo-2.3/standard/text-to-video",
        resultPath: "/fal-ai/minimax/hailuo-2.3/standard/text-to-video/requests/{request_id}",
        defaults: {"duration": "6"},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "prompt_optimizer"}],
        media: [],
    },
    {
        endpointId: "fal-ai/minimax/hailuo-2.3/standard/image-to-video",
        submitPath: "/fal-ai/minimax/hailuo-2.3/standard/image-to-video",
        resultPath: "/fal-ai/minimax/hailuo-2.3/standard/image-to-video/requests/{request_id}",
        defaults: {"duration": "6"},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "string"}, {"name": "prompt_optimizer"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true}],
    },
    {
        endpointId: "fal-ai/ltx-2.3/text-to-video",
        submitPath: "/fal-ai/ltx-2.3/text-to-video",
        resultPath: "/fal-ai/ltx-2.3/text-to-video/requests/{request_id}",
        defaults: {"duration": 6, "aspect_ratio": "16:9", "resolution": "1080p", "generate_audio": false, "fps": 25},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "number"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "fps"}],
        media: [],
    },
    {
        endpointId: "fal-ai/ltx-2.3/text-to-video/fast",
        submitPath: "/fal-ai/ltx-2.3/text-to-video/fast",
        resultPath: "/fal-ai/ltx-2.3/text-to-video/fast/requests/{request_id}",
        defaults: {"duration": 6, "aspect_ratio": "16:9", "resolution": "1080p", "generate_audio": false, "fps": 25},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "number"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "fps"}],
        media: [],
        inputConstraints: {"allOf": [{"if": {"properties": {"duration": {"exclusiveMinimum": 10}}, "required": ["duration"]}, "then": {"properties": {"fps": {"const": 25}, "resolution": {"const": "1080p"}}, "required": ["fps", "resolution"]}}]},
    },
    {
        endpointId: "fal-ai/ltx-2.3/image-to-video",
        submitPath: "/fal-ai/ltx-2.3/image-to-video",
        resultPath: "/fal-ai/ltx-2.3/image-to-video/requests/{request_id}",
        defaults: {"duration": 6, "aspect_ratio": "auto", "resolution": "1080p", "generate_audio": false, "fps": 25},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "number"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "fps"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true}, {"field": "end_image_url", "mode": "one", "role": "last", "required": false}],
    },
    {
        endpointId: "fal-ai/ltx-2.3/image-to-video/fast",
        submitPath: "/fal-ai/ltx-2.3/image-to-video/fast",
        resultPath: "/fal-ai/ltx-2.3/image-to-video/fast/requests/{request_id}",
        defaults: {"duration": 6, "aspect_ratio": "auto", "resolution": "1080p", "generate_audio": false, "fps": 25},
        fields: [{"name": "duration", "common": "seconds", "secondsFormat": "number"}, {"name": "aspect_ratio", "common": "size"}, {"name": "resolution", "common": "resolution"}, {"name": "generate_audio", "common": "generateAudio"}, {"name": "fps"}],
        media: [{"field": "image_url", "mode": "one", "role": "first", "required": true, "constraints": {"mimeTypes": ["image/png", "image/jpeg", "image/webp", "image/avif", "image/heif"]}}, {"field": "end_image_url", "mode": "one", "role": "last", "required": false}],
        inputConstraints: {"allOf": [{"if": {"properties": {"duration": {"exclusiveMinimum": 10}}, "required": ["duration"]}, "then": {"properties": {"fps": {"const": 25}, "resolution": {"const": "1080p"}}, "required": ["fps", "resolution"]}}]},
    },
];
