import axios from "axios";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { createModelChannel, defaultConfig } from "@/stores/use-config-store";
import { submitAdapterRemoteMediaTask } from "./api/remote-media-task";
import { generateResolvedMedia } from "./api/media-dispatcher";
import { runRemoteSubmitPlugin } from "./api/model-plugin";
import { encodeReferenceJpeg } from "./reference-image-codec";
import { resetReferenceImageMemoForTests, withReferenceImageSession } from "./reference-image-preparation";
vi.mock("./reference-image-codec", () => ({ encodeReferenceJpeg: vi.fn() }));
const png = "data:image/png;base64,b3JpZ2luYWw=";
const jpeg = "data:image/jpeg;base64,anBn";
beforeEach(() => { resetReferenceImageMemoForTests(); vi.mocked(encodeReferenceJpeg).mockReset().mockResolvedValue(new Blob(["jpg"], { type: "image/jpeg" })); });
afterEach(() => { vi.restoreAllMocks(); delete window.shotshot; });
test.each([true, false])("BYOK HiAPI uses shared compression (enabled=%s) and freezes retry bytes", async enabled => {
    const post = vi.spyOn(axios, "post").mockResolvedValue({ data: { data: { taskId: "task-1" } } });
    const input = { adapterId: "hiapi.image", adapterVersion: 1, config: { ...defaultConfig, compressReferenceImages: enabled, baseUrl: "https://api.hiapi.ai", apiKey: "fixture", model: "gpt-image-2/image-to-image" }, prompt: "edit", images: [png], params: {}, idempotencyKey: "same-task" };
    await submitAdapterRemoteMediaTask(input);
    input.images = ["https://changed.example/reference.png"];
    await submitAdapterRemoteMediaTask(input);
    for (const call of post.mock.calls) expect(call[1]).toMatchObject({ input: { input_urls: [enabled ? jpeg : png] } });
    expect(encodeReferenceJpeg).toHaveBeenCalledTimes(enabled ? 1 : 0);
});
test("legacy direct and remote scripts receive JPEG; masked bases retain original", async () => {
    const channel = createModelChannel({ id: "legacy", provider: "custom", apiKey: "fixture", models: [{ name: "image", capability: "image", script: "return images;" }] });
    const config = { ...defaultConfig, channels: [channel], model: "legacy::image" };
    await expect(generateResolvedMedia({ config, modality: "image", prompt: "edit", images: [png] })).resolves.toEqual({ kind: "image", sources: [jpeg] });
    await expect(runRemoteSubmitPlugin({ capability: "image", config, prompt: "edit", images: [png], script: "return { taskId: images[0] };" })).resolves.toEqual({ taskId: jpeg });
    await expect(generateResolvedMedia({ config, modality: "image", prompt: "edit", images: [png], params: { mask: png } })).resolves.toEqual({ kind: "image", sources: [png] });
});
test("OpenAI multipart and Gemini inline references carry JPEG; masked OpenAI edits keep PNG", async () => {
    const { requestOpenAIImages, requestGeminiImages } = await import("./api/image");
    const config = { ...defaultConfig, baseUrl: "https://api.example", apiKey: "fixture", model: "gpt-image-2" };
    const ref = { id: "ref", name: "original.png", type: "image/png", dataUrl: png };
    const post = vi.spyOn(axios, "post").mockResolvedValue({ data: { data: [{ b64_json: "result" }] } });
    await requestOpenAIImages(config, "edit", [ref], 1);
    const file = (post.mock.calls[0][1] as FormData).get("image") as File;
    expect(file.type).toBe("image/jpeg"); expect(file.name).toBe("original.jpg");
    const mask = { ...ref, id: "mask", name: "mask.png" };
    await requestOpenAIImages(config, "edit", [ref], 1, mask);
    const masked = post.mock.calls[1][1] as FormData;
    expect((masked.get("image") as File).type).toBe("image/png");
    expect((masked.get("mask") as File).type).toBe("image/png");
    post.mockResolvedValue({ data: { candidates: [{ content: { parts: [{ inlineData: { mimeType: "image/png", data: "result" } }] } }] } });
    await requestGeminiImages({ ...config, apiFormat: "gemini", model: "gemini-image" }, "edit", [ref], 1);
    expect(post.mock.calls[2][1]).toMatchObject({ contents: [{ parts: [{ text: "edit" }, { inlineData: { mimeType: "image/jpeg", data: "anBn" } }] }] });
    expect(ref).toMatchObject({ name: "original.png", type: "image/png", dataUrl: png });
});
